<?php include_once 'layout/header.phtml' ?>

    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <form action="/register" method="post">
                    <div class="card">

                        <div class="card-body">
                            <div class="form-group">
                                <label for="userName">Nome de Usuário</label>
                                <input type="text"
                                       class="form-control"
                                       name="userName"
                                       id="userName">
                            </div>

                            <div class="form-group">
                                <label for="password">Senha</label>
                                <input type="password"
                                       class="form-control"
                                       id="password"
                                       name="password">
                            </div>

                            <div class="form-group">
                                <label for="email">Email address</label>
                                <input type="email"
                                       class="form-control"
                                       id="email"
                                       name="email">
                            </div>

                            <div class="form-group">
                                <label for="firstName">Nome</label>
                                <input type="text"
                                       class="form-control"
                                       id="firstName"
                                       name="firstName">
                            </div>

                            <div class="form-group">
                                <label for="lastName">Email address</label>
                                <input type="text"
                                       class="form-control"
                                       id="lastName"
                                       name="lastName">
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-block btn-primary">Cadastrar-se</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php include_once 'layout/footer.phtml' ?>