<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel="shortcut icon" type="image/png" href="/public/img/shared-folder.png"/>
    <title><?=$_ENV['APP_NAME']?></title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <!--    CDN do Bootstrap-->
    <link rel="stylesheet" href="/public/css/bootstrap.css">
    <!-- Arquivo customizado de CSS-->
    <link rel="stylesheet" href="/public/css/style.css">
</head>
<body>

<header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
        <div class="container">
            <a class="navbar-brand" href="#"><?=$_ENV['APP_NAME']?></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">

                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/register">Cadastro</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>
